streaming:
  iterations:
  - 'learning.NewMemoryIterationFromCsv("dat/test_file.csv", 0, []int{1, 2, 3}, true)'
  output_condition: "&simulator.NilOutputCondition{}"
  output_function: "&simulator.NilOutputFunction{}"
  termination_condition: "&simulator.NumberOfStepsTerminationCondition{MaxNumberOfSteps: 100}"
  timestep_function: 'learning.NewMemoryTimestepFunctionFromCsv("dat/test_file.csv", 0, true)'
objectives:
- "&filter.ProbabilityFilterLogLikelihood{
    Prob: &models.GaussianProcessConditionalProbability{
    Kernel: &models.ConstantGaussianProcessCovarianceKernel{}}, 
    DataLink: &filter.NormalDataLinkingLogLikelihood{}, 
    Statistics: &filter.Statistics{}}"
objective_output: "&learning.NilObjectiveOutputFunction{}"
optimisation_algorithm: "&learning.GonumOptimisationAlgorithm{
    Method: &optimize.NelderMead{},
    Settings: &optimize.Settings{Concurrent: 10}}"