streaming:
  iterations:
  - 'learning.NewMemoryIterationFromCsv("dat/test_file.csv", 0, []int{1, 2, 3}, true)'
  output_condition: "&simulator.NilOutputCondition{}"
  output_function: "&simulator.NilOutputFunction{}"
  termination_condition: "&simulator.NumberOfStepsTerminationCondition{MaxNumberOfSteps: 99}"
  timestep_function: 'learning.NewMemoryTimestepFunctionFromCsv("dat/test_file.csv", 0, true)'
objectives:
- "&reweighting.ProbabilisticReweightingLogLikelihood{
    Prob: &models.GaussianConditionalProbability{
      Kernel: &models.ConstantGaussianCovarianceKernel{}}, 
    DataLink: &reweighting.NormalDataLinkingLogLikelihood{}, 
    Statistics: &reweighting.Statistics{}}"
objective_output: 'learning.NewJsonLogObjectiveOutputFunction("dat/test.log")'
optimisation_algorithm: "&learning.GonumOptimisationAlgorithm{
    Method: &optimize.NelderMead{},
    Settings: &optimize.Settings{Concurrent: 10}}"