other_params:
- float_params:
    initial_means: [0.0, 0.0, 0.0]
    upper_triangle_covariance_matrix: [10.0, 0.0, 0.0, 10.0, 0.0, 10.0]
  int_params:
    burn_in_steps: [5]
params_to_optimise:
- float_params:
    initial_means: [true, true, true]
    upper_triangle_covariance_matrix: [true, false, false, true, false, true]
  int_params: {}
init_state_values:
- [0.0, 0.0, 0.0]
seeds: [22113355]
state_widths: [3]
state_history_depths: [10]
timesteps_history_depth: 10