other_params:
- float_params:
    exponential_weighting_timescale: [1.0]
  float_params_mask:
    exponential_weighting_timescale: [true]
  int_params:
    burn_in_steps: [5]
init_state_values:
- [0.0, 0.0, 0.0]
init_time_value: 0.0
seeds: [22113355]
state_widths: [3]
state_history_depths: [10]
timesteps_history_depth: 10