other_params:
- float_params:
    means: [0.0, 0.0, 0.0]
    upper_triangle_cholesky_of_cov_matrix: [10.0, 0.0, 0.0, 10.0, 0.0, 10.0]
  float_params_mask:
    means: [true, true, true]
    upper_triangle_cholesky_of_cov_matrix: [true, true, true, true, true, true]
  int_params:
    burn_in_steps: [5]
init_state_values:
- [0.0, 0.0, 0.0]
init_time_value: 0.0
seeds: [22113355]
state_widths: [3]
state_history_depths: [10]
timesteps_history_depth: 10