other_params:
- float_params:
    times: []
    flattened_means_in_time: []
    upper_triangle_covariance_matrix: []
  int_params: {}
init_state_values:
- [0.0, 0.0, 0.0]
seeds: [22113355]
state_widths: [3]
state_history_depths: [10]
timesteps_history_depth: 10
burn_in_steps: 10