other_params:
- float_params:
    dummy_value: [1.0]
  int_params: {}
- float_params:
    dummy_value: [1.0]
  int_params: {}
init_state_values:
- [0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0]
seeds: [4673, 2783]
state_widths: [3, 3]
state_history_depths: [10, 10]
timesteps_history_depth: 10
burn_in_steps: 5